[package]
name = "littlefs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "~1.2.0", default-features = false }
bitfield = { version = "~0.14.0", default-features = false }
